<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="anhhn-HP-EliteBook-8470p" failures="1" tests="15" name="TestSuite.AddPatient" time="494.715" errors="0" timestamp="2022-10-27T21:54:49 ICT" skipped="0">
  <testcase classname="TestSuite.AddPatient" name="MODULE3_11" time="29.336"/>
  <testcase classname="TestSuite.AddPatient" name="MODULE3_01" time="45.298"/>
  <testcase classname="TestSuite.AddPatient" name="MODULE3_06" time="29.990"/>
  <testcase classname="TestSuite.AddPatient" name="MODULE3_07" time="25.018"/>
  <testcase classname="TestSuite.AddPatient" name="MODULE3_12" time="34.103"/>
  <testcase classname="TestSuite.AddPatient" name="MODULE3_10" time="37.874"/>
  <testcase classname="TestSuite.AddPatient" name="MODULE3_04" time="34.771"/>
  <testcase classname="TestSuite.AddPatient" name="MODULE3_09" time="30.218"/>
  <testcase classname="TestSuite.AddPatient" name="MODULE3_05" time="28.131"/>
  <testcase classname="TestSuite.AddPatient" name="MODULE3_15" time="29.538"/>
  <testcase classname="TestSuite.AddPatient" name="MODULE3_14" time="45.343">
    <failure message="Value is not correct: Expected: &quot;Ngày sinh không hợp lệ&quot;; Actual: &quot;Ngày không hợp lệ&quot;" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Value is not correct: Expected: "Ngày sinh không hợp lệ"; Actual: "Ngày không hợp lệ"
at org.testng.Assert.fail(Assert.java:97)
at Common.Utilities.assertString(Utilities.java:822)
at Common.Utilities.assertTextValue(Utilities.java:691)
at CommonScreen.AddPatientScreen.addPatient(AddPatientScreen.java:83)
at TestSuite.AddPatient.MODULE3_14(AddPatient.java:90)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:687)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:724)
at org.testng.TestRunner.run(TestRunner.java:574)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1142)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1064)
at org.testng.TestNG.runSuites(TestNG.java:994)
at org.testng.TestNG.run(TestNG.java:962)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- MODULE3_14 -->
  <testcase classname="TestSuite.AddPatient" name="MODULE3_03" time="29.076"/>
  <testcase classname="TestSuite.AddPatient" name="MODULE3_08" time="29.734"/>
  <testcase classname="TestSuite.AddPatient" name="MODULE3_13" time="31.502"/>
  <testcase classname="TestSuite.AddPatient" name="MODULE3_02" time="34.783"/>
</testsuite> <!-- TestSuite.AddPatient -->
